### ISSUE TITLE
无法潜行放置坩埚

### ISSUE THREAD

**Issue by HeartyYF** [aegistudio/MagickElement#2]
当放置一个坩埚后，按住Shift右键此坩埚只会导致打开，而不像原版那样紧贴着放置。

**Comment by aegistudio** [comment]
请尝试本插件最新版本 http://pan.baidu.com/s/1eS2kvrO ，测试前删除配置文件夹下所有文件。
Please try head revision of this plugin http://pan.baidu.com/s/1eS2kvrO , remove any file under the configuration directory before testing.
